### ISSUE TITLE
Add a QUICKSTART guide

### ISSUE THREAD

**Issue by rpappalax** [loads/loads#9]
Create a quickstart section here: http://loadsv2.readthedocs.org/en/latest/
outlining pre-requisites, as well as steps for basic (local) installation and execution of what works right now.  This will enable more folks to easily come on board, despite all the rough edges.
This would probably initially be more of a guide for how to execute a loadtest using the loads-broker locally.

**Comment by chartjes** [comment]
Moving issue to loads/loads-cli
